version: '3.7'

networks:
  backend:
    driver: bridge

services:
  web:
    build:
      context: .
      dockerfile: "Dockerfile"
    ports:
      - "8080:8080"
    restart: "unless-stopped"
    expose:
      - "8080"
    networks:
      - "backend"